# Generated by Django 5.0.1 on 2024-01-24 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blog_options_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 24, 21, 23, 56, 392609)),
        ),
    ]
